databases:
  - name: pesafast
    ipAllowList: []
    databaseName: pesafast
    user: pesafast

services:
  - type: web
    name: pesafast
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pesafast
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  #shit am adding
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction